read_formatted – DSCF-1224/gmsh_msh_format_fortran
read_formatted Subroutine
MIT
experimental
18 statements
Source File
private subroutine read_formatted(gmsh_msh_format, unit, iotype, v_list, iostat, iomsg)
Read an $MshMeshFormat from a connected formatted unit.
Arguments
Type Intent Optional Attributes Name
class(gmsh_msh_format_type), intent(inout) :: gmsh_msh_format
integer, intent(in) :: unit
character(len=*), intent(in) :: iotype
integer, intent(in) :: v_list(:)
integer, intent(out) :: iostat
character(len=*), intent(inout) :: iomsg
Calls
Called by
Source Code
    subroutine read_formatted(gmsh_msh_format, unit, iotype, v_list, iostat, iomsg)
        class(gmsh_msh_format_type), intent(inout) :: gmsh_msh_format
        integer, intent(in) :: unit
        character(*), intent(in) :: iotype
        integer, intent(in) :: v_list(:)
        integer, intent(out) :: iostat
        character(*), intent(inout) :: iomsg
        iomsg = ''
        if ( size( v_list(:) ) .gt. 0 ) then
            error stop "gmsh_msh_format_type does NOT support v_list formatters."
        end if
        select case(iotype)
            case("LISTDIRECTED")
                call read_formatted_kernel(gmsh_msh_format, unit, iostat, iomsg)
            case default
                error stop "gmsh_msh_format_type only supports the `LISTDIRECTED` iotype."
        end select
    end subroutine read_formatted
Call graph
read_formatted calls read_formatted_kernel
read_formatted_kernel calls check_text_line
read(formatted) calls read_formatted